### PR TITLE
Model works! 

### PR DESCRIPTION
**Pull request by simrantan**

### CODE REVIEW

**Comment by GemmaTuron** [comment]
HI @simrantan 
Please make sure all the metadata fits the required criteria so we can merge the changes, thanks

**Comment by GemmaTuron** [comment]
@simrantan 
make sure to use the right metadata as explained in the documentation. Remember it is case sensitive: https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/contribute-models/model-template

I'd also add COVID19 in the tags

**Comment by GemmaTuron** [comment]
@simrantan 
Almost there
the license needs to be `MIT` only

**Comment by GemmaTuron** [comment]
@simrantan 
It does not find a file:
```
Detailed error:
Model API eos8fth:run did not produce an outputTraceback (most recent call last):
  File "/home/runner/eos/repository/eos8fth/20230817170536_A0EEC0/eos8fth/artifacts/framework/code/main.py", line 75, in <module>
    output_consensus = my_model("tmp_input.smi")
  File "/home/runner/eos/repository/eos8fth/20230817170536_A0EEC0/eos8fth/artifacts/framework/code/main.py", line 49, in my_model
    get_predictions(temp_dir, temp_results_folder, csv_file)
  File "/home/runner/eos/repository/eos8fth/20230817170536_A0EEC0/eos8fth/artifacts/framework/code/run_predictions.py", line 82, in get_predictions
    features_dictn = automate(temp_dir, csv_file)
  File "/home/runner/eos/repository/eos8fth/20230817170536_A0EEC0/eos8fth/artifacts/framework/code/run_predictions.py", line 37, in automate
    dictn = json.load(open(file_path, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/eos8fth/eos8fth/eos8fth/model/framework/code/dictn_models_fp.json'
```

**Comment by simrantan** [comment]
That is strange, I will work on fixing this path

**Comment by GemmaTuron** [comment]
@simrantan 

There seems to be an issue with the fingerprint calculation. Perhaps it has to do with the temporal files that are being created, not stored in the right place?

**Comment by simrantan** [comment]
yes, I do believe that might be the issue - actions might be trying to access these files differently from cli, I am trying to see what changes could fix it

**Comment by GemmaTuron** [comment]
Hi Simran,

Please take the time needed to debug this issue before pushing so many commits, try to understand where the error might be

**Comment by simrantan** [comment]
Hi, sorry - I can close the PR for now, I push the commits so that I can test the updates locally (though the issues do not occur in my local environment so i can't tell if they are fixed until the workflow runs) but that way I can try some solutions then reopen when I am ready to test on workflows again.

**Comment by simrantan** [comment]
@GemmaTuron Everything seems to be working now! the way I was creating absolute paths worked on cli but was not compatible with actions, so I made the path creation more robust and tested locally to make sure it still works there. It seems to work everywhere fine now that the paths are fixed!

**Comment by GemmaTuron** [comment]
Hi @simrantan 
I cannot merge the PR because you deleted your fork before I could merge it? Can you recover the repo and reopen the PR?

**Pull request closed without merging**
